[project]
name = "ml-with-pytorch-sklearn"
version = "0.1.0"
description = "Environment used for the ML sklearn and pytorch book"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.6",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
]
